	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

	.align 2
Cry_CSanae::
	.incbin "sound/direct_sound_samples/cries/csanae.bin"

	.align 2
Cry_Sanae::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_CAlice::
	.incbin "sound/direct_sound_samples/cries/calice.bin"

	.align 2
Cry_Alice::
	.incbin "sound/direct_sound_samples/cries/alice.bin"

	.align 2
Cry_CReisen::
	.incbin "sound/direct_sound_samples/cries/creisen.bin"

	.align 2
Cry_Reisen::
	.incbin "sound/direct_sound_samples/cries/reisen.bin"

	.align 2
Cry_CLilyWhite::
	.incbin "sound/direct_sound_samples/cries/clilywhite.bin"

	.align 2
Cry_LilyWhite::
	.incbin "sound/direct_sound_samples/cries/lilywhite.bin"

	.align 2
Cry_CLilyBlack::
	.incbin "sound/direct_sound_samples/cries/clilyblack.bin"

	.align 2
Cry_LilyBlack::
	.incbin "sound/direct_sound_samples/cries/lilyblack.bin"

	.align 2
Cry_CMomiji::
	.incbin "sound/direct_sound_samples/cries/cmomiji.bin"

	.align 2
Cry_Momiji::
	.incbin "sound/direct_sound_samples/cries/momiji.bin"

	.align 2
Cry_CShizuha::
	.incbin "sound/direct_sound_samples/cries/cshizuha.bin"

	.align 2
Cry_Shizuha::
	.incbin "sound/direct_sound_samples/cries/shizuha.bin"

	.align 2
Cry_CMedicine::
	.incbin "sound/direct_sound_samples/cries/cmedicine.bin"

	.align 2
Cry_Medicine::
	.incbin "sound/direct_sound_samples/cries/medicine.bin"

	.align 2
Cry_CKoakuma::
	.incbin "sound/direct_sound_samples/cries/ckoakuma.bin"

	.align 2
Cry_Koakuma::
	.incbin "sound/direct_sound_samples/cries/koakuma.bin"

	.align 2
Cry_CNazrin::
	.incbin "sound/direct_sound_samples/cries/cnazrin.bin"

	.align 2
Cry_Nazrin::
	.incbin "sound/direct_sound_samples/cries/nazrin.bin"

	.align 2
Cry_CTokiko::
	.incbin "sound/direct_sound_samples/cries/ctokiko.bin"

	.align 2
Cry_Tokiko::
	.incbin "sound/direct_sound_samples/cries/tokiko.bin"

	.align 2
Cry_CRemilia::
	.incbin "sound/direct_sound_samples/cries/cremilia.bin"

	.align 2
Cry_Remilia::
	.incbin "sound/direct_sound_samples/cries/remilia.bin"

	.align 2
Cry_CCirno::
	.incbin "sound/direct_sound_samples/cries/ccirno.bin"

	.align 2
Cry_Cirno::
	.incbin "sound/direct_sound_samples/cries/cirno.bin"

	.align 2
Cry_CRumia::
	.incbin "sound/direct_sound_samples/cries/crumia.bin"

	.align 2
Cry_Rumia::
	.incbin "sound/direct_sound_samples/cries/rumia.bin"

	.align 2
Cry_Shanghai::
	.incbin "sound/direct_sound_samples/cries/shanghai.bin"

	.align 2
Cry_CFlandre::
	.incbin "sound/direct_sound_samples/cries/cflandre.bin"

	.align 2
Cry_Flandre::
	.incbin "sound/direct_sound_samples/cries/flandre.bin"

	.align 2
Cry_Hourai::
	.incbin "sound/direct_sound_samples/cries/hourai.bin"

	.align 2
Cry_CYoumu::
	.incbin "sound/direct_sound_samples/cries/cyoumu.bin"

	.align 2
Cry_Youmu::
	.incbin "sound/direct_sound_samples/cries/youmu.bin"

	.align 2
Cry_CYukari::
	.incbin "sound/direct_sound_samples/cries/cyukari.bin"

	.align 2
Cry_Yukari::
	.incbin "sound/direct_sound_samples/cries/yukari.bin"

	.align 2
Cry_CSuika::
	.incbin "sound/direct_sound_samples/cries/csuika.bin"

	.align 2
Cry_Suika::
	.incbin "sound/direct_sound_samples/cries/suika.bin"

	.align 2
Cry_CMystia::
	.incbin "sound/direct_sound_samples/cries/cmystia.bin"

	.align 2
Cry_Mystia::
	.incbin "sound/direct_sound_samples/cries/mystia.bin"

	.align 2
Cry_CMinoriko::
	.incbin "sound/direct_sound_samples/cries/cminoriko.bin"

	.align 2
Cry_Minoriko::
	.incbin "sound/direct_sound_samples/cries/minoriko.bin"

	.align 2
Cry_CKeine::
	.incbin "sound/direct_sound_samples/cries/ckeine.bin"

	.align 2
Cry_Keine::
	.incbin "sound/direct_sound_samples/cries/keine.bin"

	.align 2
Cry_AKeine::
	.incbin "sound/direct_sound_samples/cries/akeine.bin"

	.align 2
Cry_CIku::
	.incbin "sound/direct_sound_samples/cries/ciku.bin"

	.align 2
Cry_Iku::
	.incbin "sound/direct_sound_samples/cries/iku.bin"

	.align 2
Cry_CKoishi::
	.incbin "sound/direct_sound_samples/cries/ckoishi.bin"

	.align 2
Cry_Koishi::
	.incbin "sound/direct_sound_samples/cries/koishi.bin"

	.align 2
Cry_CYamame::
	.incbin "sound/direct_sound_samples/cries/cyamame.bin"

	.align 2
Cry_Yamame::
	.incbin "sound/direct_sound_samples/cries/yamame.bin"

	.align 2
Cry_CChen::
	.incbin "sound/direct_sound_samples/cries/cchen.bin"

	.align 2
Cry_Chen::
	.incbin "sound/direct_sound_samples/cries/chen.bin"

	.align 2
Cry_CYorihime::
	.incbin "sound/direct_sound_samples/cries/cyorihime.bin"

	.align 2
Cry_Yorihime::
	.incbin "sound/direct_sound_samples/cries/yorihime.bin"

	.align 2
Cry_CKaguya::
	.incbin "sound/direct_sound_samples/cries/ckaguya.bin"

	.align 2
Cry_Kaguya::
	.incbin "sound/direct_sound_samples/cries/kaguya.bin"

	.align 2
Cry_CMokou::
	.incbin "sound/direct_sound_samples/cries/cmokou.bin"

	.align 2
Cry_Mokou::
	.incbin "sound/direct_sound_samples/cries/mokou.bin"

	.align 2
Cry_CHatate::
	.incbin "sound/direct_sound_samples/cries/chatate.bin"

	.align 2
Cry_Hatate::
	.incbin "sound/direct_sound_samples/cries/hatate.bin"

	.align 2
Cry_CLetty::
	.incbin "sound/direct_sound_samples/cries/cletty.bin"

	.align 2
Cry_Letty::
	.incbin "sound/direct_sound_samples/cries/letty.bin"

	.align 2
Cry_CPatchouli::
	.incbin "sound/direct_sound_samples/cries/cpatchouli.bin"

	.align 2
Cry_Patchouli::
	.incbin "sound/direct_sound_samples/cries/patchouli.bin"

	.align 2
Cry_CYuugi::
	.incbin "sound/direct_sound_samples/cries/cyuugi.bin"

	.align 2
Cry_Yuugi::
	.incbin "sound/direct_sound_samples/cries/yuugi.bin"

	.align 2
Cry_CTenshi::
	.incbin "sound/direct_sound_samples/cries/ctenshi.bin"

	.align 2
Cry_Tenshi::
	.incbin "sound/direct_sound_samples/cries/tenshi.bin"

	.align 2
Cry_CParsee::
	.incbin "sound/direct_sound_samples/cries/cparsee.bin"

	.align 2
Cry_Parsee::
	.incbin "sound/direct_sound_samples/cries/parsee.bin"

	.align 2
Cry_CMurasa::
	.incbin "sound/direct_sound_samples/cries/cmurasa.bin"

	.align 2
Cry_Murasa::
	.incbin "sound/direct_sound_samples/cries/murasa.bin"

	.align 2
Cry_CKisume::
	.incbin "sound/direct_sound_samples/cries/ckisume.bin"

	.align 2
Cry_Kisume::
	.incbin "sound/direct_sound_samples/cries/kisume.bin"

	.align 2
Cry_CKogasa::
	.incbin "sound/direct_sound_samples/cries/ckogasa.bin"

	.align 2
Cry_Kogasa::
	.incbin "sound/direct_sound_samples/cries/kogasa.bin"

	.align 2
Cry_CSatori::
	.incbin "sound/direct_sound_samples/cries/csatori.bin"

	.align 2
Cry_Satori::
	.incbin "sound/direct_sound_samples/cries/satori.bin"

	.align 2
Cry_CEirin::
	.incbin "sound/direct_sound_samples/cries/ceirin.bin"

	.align 2
Cry_Eirin::
	.incbin "sound/direct_sound_samples/cries/eirin.bin"

	.align 2
Cry_CRan::
	.incbin "sound/direct_sound_samples/cries/cran.bin"

	.align 2
Cry_Ran::
	.incbin "sound/direct_sound_samples/cries/ran.bin"

	.align 2
Cry_CDaiyousei::
	.incbin "sound/direct_sound_samples/cries/cdaiyousei.bin"

	.align 2
Cry_Daiyousei::
	.incbin "sound/direct_sound_samples/cries/daiyousei.bin"

	.align 2
Cry_CNitori::
	.incbin "sound/direct_sound_samples/cries/cnitori.bin"

	.align 2
Cry_Nitori::
	.incbin "sound/direct_sound_samples/cries/nitori.bin"

	.align 2
Cry_CHina::
	.incbin "sound/direct_sound_samples/cries/china.bin"

	.align 2
Cry_Hina::
	.incbin "sound/direct_sound_samples/cries/hina.bin"

	.align 2
Cry_CKomachi::
	.incbin "sound/direct_sound_samples/cries/ckomachi.bin"

	.align 2
Cry_Komachi::
	.incbin "sound/direct_sound_samples/cries/komachi.bin"

	.align 2
Cry_CYuyuko::
	.incbin "sound/direct_sound_samples/cries/cyuyuko.bin"

	.align 2
Cry_Yuyuko::
	.incbin "sound/direct_sound_samples/cries/yuyuko.bin"

	.align 2
Cry_CMeiling::
	.incbin "sound/direct_sound_samples/cries/cmeiling.bin"

	.align 2
Cry_Meiling::
	.incbin "sound/direct_sound_samples/cries/meiling.bin"

	.align 2
Cry_CSakuya::
	.incbin "sound/direct_sound_samples/cries/csakuya.bin"

	.align 2
Cry_Sakuya::
	.incbin "sound/direct_sound_samples/cries/sakuya.bin"

	.align 2
Cry_CLunasa::
	.incbin "sound/direct_sound_samples/cries/clunasa.bin"

	.align 2
Cry_Lunasa::
	.incbin "sound/direct_sound_samples/cries/lunasa.bin"

	.align 2
Cry_CMerlin::
	.incbin "sound/direct_sound_samples/cries/cmerlin.bin"

	.align 2
Cry_Merlin::
	.incbin "sound/direct_sound_samples/cries/merlin.bin"

	.align 2
Cry_CLyrica::
	.incbin "sound/direct_sound_samples/cries/clyrica.bin"

	.align 2
Cry_Lyrica::
	.incbin "sound/direct_sound_samples/cries/lyrica.bin"

	.align 2
Cry_CLayla::
	.incbin "sound/direct_sound_samples/cries/clayla.bin"

	.align 2
Cry_Layla::
	.incbin "sound/direct_sound_samples/cries/layla.bin"

	.align 2
Cry_CKanako::
	.incbin "sound/direct_sound_samples/cries/ckanako.bin"

	.align 2
Cry_Kanako::
	.incbin "sound/direct_sound_samples/cries/kanako.bin"

	.align 2
Cry_CRin::
	.incbin "sound/direct_sound_samples/cries/crin.bin"

	.align 2
Cry_Rin::
	.incbin "sound/direct_sound_samples/cries/rin.bin"

	.align 2
Cry_CUtsuho::
	.incbin "sound/direct_sound_samples/cries/cutsuho.bin"

	.align 2
Cry_Utsuho::
	.incbin "sound/direct_sound_samples/cries/utsuho.bin"

	.align 2
Cry_CIchirin::
	.incbin "sound/direct_sound_samples/cries/cichirin.bin"

	.align 2
Cry_Ichirin::
	.incbin "sound/direct_sound_samples/cries/ichirin.bin"

	.align 2
Cry_CSunnyMilk::
	.incbin "sound/direct_sound_samples/cries/csunnymilk.bin"

	.align 2
Cry_SunnyMilk::
	.incbin "sound/direct_sound_samples/cries/sunnymilk.bin"

	.align 2
Cry_CLunaChild::
	.incbin "sound/direct_sound_samples/cries/clunachild.bin"

	.align 2
Cry_LunaChild::
	.incbin "sound/direct_sound_samples/cries/lunachild.bin"

	.align 2
Cry_CStarSapphire::
	.incbin "sound/direct_sound_samples/cries/cstarsapphire.bin"

	.align 2
Cry_StarSapphire::
	.incbin "sound/direct_sound_samples/cries/starsapphire.bin"

	.align 2
Cry_CYuuka::
	.incbin "sound/direct_sound_samples/cries/cyuuka.bin"

	.align 2
Cry_Yuuka::
	.incbin "sound/direct_sound_samples/cries/yuuka.bin"

	.align 2
Cry_CAya::
	.incbin "sound/direct_sound_samples/cries/caya.bin"

	.align 2
Cry_Aya::
	.incbin "sound/direct_sound_samples/cries/aya.bin"

	.align 2
Cry_CShikieiki::
	.incbin "sound/direct_sound_samples/cries/cshikieiki.bin"

	.align 2
Cry_Shikieiki::
	.incbin "sound/direct_sound_samples/cries/shikieiki.bin"

	.align 2
Cry_CShou::
	.incbin "sound/direct_sound_samples/cries/cshou.bin"

	.align 2
Cry_Shou::
	.incbin "sound/direct_sound_samples/cries/shou.bin"

	.align 2
Cry_CWriggle::
	.incbin "sound/direct_sound_samples/cries/cwriggle.bin"

	.align 2
Cry_Wriggle::
	.incbin "sound/direct_sound_samples/cries/wriggle.bin"

	.align 2
Cry_CTewi::
	.incbin "sound/direct_sound_samples/cries/ctewi.bin"

	.align 2
Cry_Tewi::
	.incbin "sound/direct_sound_samples/cries/tewi.bin"

	.align 2
Cry_Kedama::
	.incbin "sound/direct_sound_samples/cries/kedama.bin"

	.align 2
Cry_CNue::
	.incbin "sound/direct_sound_samples/cries/cnue.bin"

	.align 2
Cry_Nue::
	.incbin "sound/direct_sound_samples/cries/nue.bin"

	.align 2
Cry_CSuwako::
	.incbin "sound/direct_sound_samples/cries/csuwako.bin"

	.align 2
Cry_Suwako::
	.incbin "sound/direct_sound_samples/cries/suwako.bin"

	.align 2
Cry_ReisenII::
	.incbin "sound/direct_sound_samples/cries/reisenii.bin"

	.align 2
Cry_CMarisa::
	.incbin "sound/direct_sound_samples/cries/cmarisa.bin"

	.align 2
Cry_Marisa::
	.incbin "sound/direct_sound_samples/cries/marisa.bin"

	.align 2
Cry_CReimu::
	.incbin "sound/direct_sound_samples/cries/creimu.bin"

	.align 2
Cry_Reimu::
	.incbin "sound/direct_sound_samples/cries/reimu.bin"

	.align 2
Cry_CByakuren::
	.incbin "sound/direct_sound_samples/cries/cbyakuren.bin"

	.align 2
Cry_Byakuren::
	.incbin "sound/direct_sound_samples/cries/byakuren.bin"

	.align 2
Cry_Konngara::
	.incbin "sound/direct_sound_samples/cries/konngara.bin"

	.align 2
Cry_Kikuri::
	.incbin "sound/direct_sound_samples/cries/kikuri.bin"

	.align 2
Cry_YuugenMagan::
	.incbin "sound/direct_sound_samples/cries/yuugenmagan.bin"

	.align 2
Cry_CToyohime::
	.incbin "sound/direct_sound_samples/cries/ctoyohime.bin"

	.align 2
Cry_Toyohime::
	.incbin "sound/direct_sound_samples/cries/toyohime.bin"

	.align 2
Cry_Goliath::
	.incbin "sound/direct_sound_samples/cries/goliath.bin"

	.align 2
Cry_Sariel::
	.incbin "sound/direct_sound_samples/cries/sariel.bin"

	.align 2
Cry_Akyuu::
	.incbin "sound/direct_sound_samples/cries/akyuu.bin"

	.align 2
Cry_Genjii::
	.incbin "sound/direct_sound_samples/cries/genjii.bin"

	.align 2
Cry_Tori::
	.incbin "sound/direct_sound_samples/cries/tori.bin"

	.align 2
Cry_Namazu::
	.incbin "sound/direct_sound_samples/cries/namazu.bin"

	.align 2
Cry_CElly::
	.incbin "sound/direct_sound_samples/cries/celly.bin"

	.align 2
Cry_Elly::
	.incbin "sound/direct_sound_samples/cries/elly.bin"

	.align 2
Cry_COrange::
	.incbin "sound/direct_sound_samples/cries/corange.bin"

	.align 2
Cry_Orange::
	.incbin "sound/direct_sound_samples/cries/orange.bin"

	.align 2
Cry_Youki::
	.incbin "sound/direct_sound_samples/cries/youki.bin"

	.align 2
Cry_CChiyuri::
	.incbin "sound/direct_sound_samples/cries/cchiyuri.bin"

	.align 2
Cry_Chiyuri::
	.incbin "sound/direct_sound_samples/cries/chiyuri.bin"

	.align 2
Cry_CYumemi::
	.incbin "sound/direct_sound_samples/cries/cyumemi.bin"

	.align 2
Cry_Yumemi::
	.incbin "sound/direct_sound_samples/cries/yumemi.bin"

	.align 2
Cry_CEllen::
	.incbin "sound/direct_sound_samples/cries/cellen.bin"

	.align 2
Cry_Ellen::
	.incbin "sound/direct_sound_samples/cries/ellen.bin"

	.align 2
Cry_CKazami::
	.incbin "sound/direct_sound_samples/cries/ckazami.bin"

	.align 2
Cry_Kazami::
	.incbin "sound/direct_sound_samples/cries/kazami.bin"

	.align 2
Cry_CMeira::
	.incbin "sound/direct_sound_samples/cries/cmeira.bin"

	.align 2
Cry_Meira::
	.incbin "sound/direct_sound_samples/cries/meira.bin"

	.align 2
Cry_CSara::
	.incbin "sound/direct_sound_samples/cries/csara.bin"

	.align 2
Cry_Sara::
	.incbin "sound/direct_sound_samples/cries/sara.bin"

	.align 2
Cry_CLuize::
	.incbin "sound/direct_sound_samples/cries/cluize.bin"

	.align 2
Cry_Luize::
	.incbin "sound/direct_sound_samples/cries/luize.bin"

	.align 2
Cry_CMargatroid::
	.incbin "sound/direct_sound_samples/cries/cmargatroid.bin"

	.align 2
Cry_Margatroid::
	.incbin "sound/direct_sound_samples/cries/margatroid.bin"

	.align 2
Cry_CKana::
	.incbin "sound/direct_sound_samples/cries/ckana.bin"

	.align 2
Cry_Kana::
	.incbin "sound/direct_sound_samples/cries/kana.bin"

	.align 2
Cry_CHakurei::
	.incbin "sound/direct_sound_samples/cries/chakurei.bin"

	.align 2
Cry_Hakurei::
	.incbin "sound/direct_sound_samples/cries/hakurei.bin"

	.align 2
Cry_CKirisame::
	.incbin "sound/direct_sound_samples/cries/ckirisame.bin"

	.align 2
Cry_Kirisame::
	.incbin "sound/direct_sound_samples/cries/kirisame.bin"

	.align 2
Cry_CKotohime::
	.incbin "sound/direct_sound_samples/cries/ckotohime.bin"

	.align 2
Cry_Kotohime::
	.incbin "sound/direct_sound_samples/cries/kotohime.bin"

	.align 2
Cry_CYumeko::
	.incbin "sound/direct_sound_samples/cries/cyumeko.bin"

	.align 2
Cry_Yumeko::
	.incbin "sound/direct_sound_samples/cries/yumeko.bin"

	.align 2
Cry_CShinki::
	.incbin "sound/direct_sound_samples/cries/cshinki.bin"

	.align 2
Cry_Shinki::
	.incbin "sound/direct_sound_samples/cries/shinki.bin"

	.align 2
Cry_MimiChan::
	.incbin "sound/direct_sound_samples/cries/mimichan.bin"

	.align 2
Cry_Ruukoto::
	.incbin "sound/direct_sound_samples/cries/ruukoto.bin"

	.align 2
Cry_CRika::
	.incbin "sound/direct_sound_samples/cries/crika.bin"

	.align 2
Cry_Rika::
	.incbin "sound/direct_sound_samples/cries/rika.bin"

	.align 2
Cry_CMugetsu::
	.incbin "sound/direct_sound_samples/cries/cmugetsu.bin"

	.align 2
Cry_Mugetsu::
	.incbin "sound/direct_sound_samples/cries/mugetsu.bin"

	.align 2
Cry_CGengetsu::
	.incbin "sound/direct_sound_samples/cries/cgengetsu.bin"

	.align 2
Cry_Gengetsu::
	.incbin "sound/direct_sound_samples/cries/gengetsu.bin"

	.align 2
Cry_CKurumi::
	.incbin "sound/direct_sound_samples/cries/ckurumi.bin"

	.align 2
Cry_Kurumi::
	.incbin "sound/direct_sound_samples/cries/kurumi.bin"

	.align 2
Cry_CRikako::
	.incbin "sound/direct_sound_samples/cries/crikako.bin"

	.align 2
Cry_Rikako::
	.incbin "sound/direct_sound_samples/cries/rikako.bin"

	.align 2
Cry_CYuki::
	.incbin "sound/direct_sound_samples/cries/cyuki.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/unown.bin"

	.align 2
Cry_CMai::
	.incbin "sound/direct_sound_samples/cries/cmai.bin"

	.align 2
Cry_Mai::
	.incbin "sound/direct_sound_samples/cries/mai.bin"

	.align 2
Cry_DSunnyMilk::
	.incbin "sound/direct_sound_samples/cries/dsunnymilk.bin"

	.align 2
Cry_TLunaChild::
	.incbin "sound/direct_sound_samples/cries/tlunachild.bin"

	.align 2
Cry_HStarSapphire::
	.incbin "sound/direct_sound_samples/cries/hstarsapphire.bin"

	.align 2
Cry_ANitori::
	.incbin "sound/direct_sound_samples/cries/anitori.bin"

	.align 2
Cry_TNitori::
	.incbin "sound/direct_sound_samples/cries/tnitori.bin"

	.align 2
Cry_AMokou::
	.incbin "sound/direct_sound_samples/cries/amokou.bin"

	.align 2
Cry_DMokou::
	.incbin "sound/direct_sound_samples/cries/dmokou.bin"

	.align 2
Cry_DReisen::
	.incbin "sound/direct_sound_samples/cries/dreisen.bin"

	.align 2
Cry_TReisen::
	.incbin "sound/direct_sound_samples/cries/treisen.bin"

	.align 2
Cry_TSakuya::
	.incbin "sound/direct_sound_samples/cries/tsakuya.bin"

	.align 2
Cry_HSakuya::
	.incbin "sound/direct_sound_samples/cries/hsakuya.bin"

	.align 2
Cry_ARumia::
	.incbin "sound/direct_sound_samples/cries/arumia.bin"

	.align 2
Cry_SRumia::
	.incbin "sound/direct_sound_samples/cries/srumia.bin"

	.align 2
Cry_HMystia::
	.incbin "sound/direct_sound_samples/cries/hmystia.bin"

	.align 2
Cry_AMystia::
	.incbin "sound/direct_sound_samples/cries/amystia.bin"

	.align 2
Cry_AChen::
	.incbin "sound/direct_sound_samples/cries/achen.bin"

	.align 2
Cry_TChen::
	.incbin "sound/direct_sound_samples/cries/tchen.bin"

	.align 2
Cry_DYoumu::
	.incbin "sound/direct_sound_samples/cries/dyoumu.bin"

	.align 2
Cry_SYoumu::
	.incbin "sound/direct_sound_samples/cries/syoumu.bin"

	.align 2
Cry_AYuuka::
	.incbin "sound/direct_sound_samples/cries/ayuuka.bin"

	.align 2
Cry_TYuuka::
	.incbin "sound/direct_sound_samples/cries/tyuuka.bin"

	.align 2
Cry_SAya::
	.incbin "sound/direct_sound_samples/cries/saya.bin"

	.align 2
Cry_TAya::
	.incbin "sound/direct_sound_samples/cries/taya.bin"

	.align 2
Cry_ATenshi::
	.incbin "sound/direct_sound_samples/cries/atenshi.bin"

	.align 2
Cry_DTenshi::
	.incbin "sound/direct_sound_samples/cries/dtenshi.bin"

	.align 2
Cry_DParsee::
	.incbin "sound/direct_sound_samples/cries/dparsee.bin"

	.align 2
Cry_TParsee::
	.incbin "sound/direct_sound_samples/cries/tparsee.bin"

	.align 2
Cry_AKoishi::
	.incbin "sound/direct_sound_samples/cries/akoishi.bin"

	.align 2
Cry_SKoishi::
	.incbin "sound/direct_sound_samples/cries/skoishi.bin"

	.align 2
Cry_DByakuren::
	.incbin "sound/direct_sound_samples/cries/dbyakuren.bin"

	.align 2
Cry_TByakuren::
	.incbin "sound/direct_sound_samples/cries/tbyakuren.bin"

	.align 2
Cry_DIchirin::
	.incbin "sound/direct_sound_samples/cries/dichirin.bin"

	.align 2
Cry_TIchirin::
	.incbin "sound/direct_sound_samples/cries/tichirin.bin"

	.align 2
Cry_AKanako::
	.incbin "sound/direct_sound_samples/cries/akanako.bin"

	.align 2
Cry_DKanako::
	.incbin "sound/direct_sound_samples/cries/dkanako.bin"

	.align 2
Cry_AKaguya::
	.incbin "sound/direct_sound_samples/cries/akaguya.bin"

	.align 2
Cry_DKaguya::
	.incbin "sound/direct_sound_samples/cries/dkaguya.bin"

	.align 2
Cry_ShinGyokuO::
	.incbin "sound/direct_sound_samples/cries/shingyokuo.bin"

	.align 2
Cry_ShinGyokuM::
	.incbin "sound/direct_sound_samples/cries/shingyokum.bin"

	.align 2
Cry_ShinGyokuF::
	.incbin "sound/direct_sound_samples/cries/shingyokuf.bin"

	.align 2
Cry_AUtsuho::
	.incbin "sound/direct_sound_samples/cries/autsuho.bin"

	.align 2
Cry_SUtsuho::
	.incbin "sound/direct_sound_samples/cries/sutsuho.bin"

	.align 2
Cry_DMomiji::
	.incbin "sound/direct_sound_samples/cries/dmomiji.bin"

	.align 2
Cry_Elis::
	.incbin "sound/direct_sound_samples/cries/elis.bin"

	.align 2
Cry_Mima::
	.incbin "sound/direct_sound_samples/cries/mima.bin"

	.align 2
Cry_SKomachi::
	.incbin "sound/direct_sound_samples/cries/skomachi.bin"

	.align 2
Cry_AKomachi::
	.incbin "sound/direct_sound_samples/cries/akomachi.bin"

	.align 2
Cry_AEirin::
	.incbin "sound/direct_sound_samples/cries/aeirin.bin"

	.align 2
Cry_SWriggle::
	.incbin "sound/direct_sound_samples/cries/swriggle.bin"

	.align 2
Cry_AdReisen::
	.incbin "sound/direct_sound_samples/cries/adreisen.bin"

	.align 2
Cry_CSariel::
	.incbin "sound/direct_sound_samples/cries/csariel.bin"

	.align 2
Cry_AShikieiki::
	.incbin "sound/direct_sound_samples/cries/ashikieiki.bin"

	.align 2
Cry_TToyohime::
	.incbin "sound/direct_sound_samples/cries/ttoyohime.bin"

	.align 2
Cry_Rinnosuke::
	.incbin "sound/direct_sound_samples/cries/rinnosuke.bin"

	.align 2
Cry_Mamizou::
	.incbin "sound/direct_sound_samples/cries/mamizou.bin"

	.align 2
Cry_AMinoriko::
	.incbin "sound/direct_sound_samples/cries/aminoriko.bin"

	.align 2
Cry_TSatori::
	.incbin "sound/direct_sound_samples/cries/tsatori.bin"

	.align 2
Cry_DShikieiki::
	.incbin "sound/direct_sound_samples/cries/dshikieiki.bin"

	.align 2
Cry_DSatori::
	.incbin "sound/direct_sound_samples/cries/dsatori.bin"

	.align 2
Cry_CShinGyoku::
	.incbin "sound/direct_sound_samples/cries/cshingyoku.bin"

	.align 2
Cry_DIku::
	.incbin "sound/direct_sound_samples/cries/diku.bin"

	.align 2
Cry_TIku::
	.incbin "sound/direct_sound_samples/cries/tiku.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cries/unused_265.bin"

	.align 2
Cry_TShou::
	.incbin "sound/direct_sound_samples/cries/tshou.bin"

	.align 2
Cry_ATokiko::
	.incbin "sound/direct_sound_samples/cries/atokiko.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cries/unused_268.bin"

	.align 2
Cry_SKogasa::
	.incbin "sound/direct_sound_samples/cries/skogasa.bin"

	.align 2
Cry_AAlice::
	.incbin "sound/direct_sound_samples/cries/aalice.bin"

	.align 2
Cry_TAlice::
	.incbin "sound/direct_sound_samples/cries/talice.bin"

	.align 2
Cry_AReimu::
	.incbin "sound/direct_sound_samples/cries/areimu.bin"

	.align 2
Cry_HEirin::
	.incbin "sound/direct_sound_samples/cries/heirin.bin"

	.align 2
Cry_DYukari::
	.incbin "sound/direct_sound_samples/cries/dyukari.bin"

	.align 2
Cry_TYukari::
	.incbin "sound/direct_sound_samples/cries/tyukari.bin"

	.align 2
Cry_DReimu::
	.incbin "sound/direct_sound_samples/cries/dreimu.bin"

	.align 2
Cry_SCirno::
	.incbin "sound/direct_sound_samples/cries/scirno.bin"

	.align 2
Cry_TCirno::
	.incbin "sound/direct_sound_samples/cries/tcirno.bin"

	.align 2
Cry_DRemilia::
	.incbin "sound/direct_sound_samples/cries/dremilia.bin"

	.align 2
Cry_TKogasa::
	.incbin "sound/direct_sound_samples/cries/tkogasa.bin"

	.align 2
Cry_TYamame::
	.incbin "sound/direct_sound_samples/cries/tyamame.bin"

	.align 2
Cry_DDaiyousei::
	.incbin "sound/direct_sound_samples/cries/ddaiyousei.bin"

	.align 2
Cry_AHina::
	.incbin "sound/direct_sound_samples/cries/ahina.bin"

	.align 2
Cry_DHina::
	.incbin "sound/direct_sound_samples/cries/dhina.bin"

	.align 2
Cry_SShizuha::
	.incbin "sound/direct_sound_samples/cries/sshizuha.bin"

	.align 2
Cry_SRin::
	.incbin "sound/direct_sound_samples/cries/srin.bin"

	.align 2
Cry_ARin::
	.incbin "sound/direct_sound_samples/cries/arin.bin"

	.align 2
Cry_ZombieFairy::
	.incbin "sound/direct_sound_samples/cries/zombiefairy.bin"

	.align 2
Cry_ATewi::
	.incbin "sound/direct_sound_samples/cries/atewi.bin"

	.align 2
Cry_HLyrica::
	.incbin "sound/direct_sound_samples/cries/hlyrica.bin"

	.align 2
Cry_ARan::
	.incbin "sound/direct_sound_samples/cries/aran.bin"

	.align 2
Cry_HRan::
	.incbin "sound/direct_sound_samples/cries/hran.bin"

	.align 2
Cry_AMedicine::
	.incbin "sound/direct_sound_samples/cries/amedicine.bin"

	.align 2
Cry_TMedicine::
	.incbin "sound/direct_sound_samples/cries/tmedicine.bin"

	.align 2
Cry_Tenma::
	.incbin "sound/direct_sound_samples/cries/tenma.bin"

	.align 2
Cry_Sendai::
	.incbin "sound/direct_sound_samples/cries/sendai.bin"

	.align 2
Cry_CKyouko::
	.incbin "sound/direct_sound_samples/cries/ckyouko.bin"

	.align 2
Cry_SSariel::
	.incbin "sound/direct_sound_samples/cries/ssariel.bin"

	.align 2
Cry_ALilyWhite::
	.incbin "sound/direct_sound_samples/cries/alilywhite.bin"

	.align 2
Cry_CMima::
	.incbin "sound/direct_sound_samples/cries/cmima.bin"

	.align 2
Cry_HShizuha::
	.incbin "sound/direct_sound_samples/cries/hshizuha.bin"

	.align 2
Cry_ASuwako::
	.incbin "sound/direct_sound_samples/cries/asuwako.bin"

	.align 2
Cry_AShou::
	.incbin "sound/direct_sound_samples/cries/ashou.bin"

	.align 2
Cry_AFlandre::
	.incbin "sound/direct_sound_samples/cries/aflandre.bin"

	.align 2
Cry_ADaiyousei::
	.incbin "sound/direct_sound_samples/cries/adaiyousei.bin"

	.align 2
Cry_CElis::
	.incbin "sound/direct_sound_samples/cries/celis.bin"

	.align 2
Cry_DLetty::
	.incbin "sound/direct_sound_samples/cries/dletty.bin"

	.align 2
Cry_TNazrin::
	.incbin "sound/direct_sound_samples/cries/tnazrin.bin"

	.align 2
Cry_HNazrin::
	.incbin "sound/direct_sound_samples/cries/hnazrin.bin"

	.align 2
Cry_SFlandre::
	.incbin "sound/direct_sound_samples/cries/sflandre.bin"

	.align 2
Cry_DWriggle::
	.incbin "sound/direct_sound_samples/cries/dwriggle.bin"

	.align 2
Cry_ASunnyMilk::
	.incbin "sound/direct_sound_samples/cries/asunnymilk.bin"

	.align 2
Cry_ALunaChild::
	.incbin "sound/direct_sound_samples/cries/alunachild.bin"

	.align 2
Cry_CKikuri::
	.incbin "sound/direct_sound_samples/cries/ckikuri.bin"

	.align 2
Cry_AdMeiling::
	.incbin "sound/direct_sound_samples/cries/admeiling.bin"

	.align 2
Cry_CKonngara::
	.incbin "sound/direct_sound_samples/cries/ckonngara.bin"

	.align 2
Cry_CYuugenMagan::
	.incbin "sound/direct_sound_samples/cries/cyuugenmagan.bin"

	.align 2
Cry_THatate::
	.incbin "sound/direct_sound_samples/cries/thatate.bin"

	.align 2
Cry_DHatate::
	.incbin "sound/direct_sound_samples/cries/dhatate.bin"

	.align 2
Cry_DLayla::
	.incbin "sound/direct_sound_samples/cries/dlayla.bin"

	.align 2
Cry_DKeine::
	.incbin "sound/direct_sound_samples/cries/dkeine.bin"

	.align 2
Cry_ALilyBlack::
	.incbin "sound/direct_sound_samples/cries/alilyblack.bin"

	.align 2
Cry_DYuugi::
	.incbin "sound/direct_sound_samples/cries/dyuugi.bin"

	.align 2
Cry_DMinoriko::
	.incbin "sound/direct_sound_samples/cries/dminoriko.bin"

	.align 2
Cry_TSuika::
	.incbin "sound/direct_sound_samples/cries/tsuika.bin"

	.align 2
Cry_ASanae::
	.incbin "sound/direct_sound_samples/cries/asanae.bin"

	.align 2
Cry_ANue::
	.incbin "sound/direct_sound_samples/cries/anue.bin"

	.align 2
Cry_TNue::
	.incbin "sound/direct_sound_samples/cries/tnue.bin"

	.align 2
Cry_HKoakuma::
	.incbin "sound/direct_sound_samples/cries/hkoakuma.bin"

	.align 2
Cry_SMeiling::
	.incbin "sound/direct_sound_samples/cries/smeiling.bin"

	.align 2
Cry_HLetty::
	.incbin "sound/direct_sound_samples/cries/hletty.bin"

	.align 2
Cry_SYorihime::
	.incbin "sound/direct_sound_samples/cries/syorihime.bin"

	.align 2
Cry_ARemilia::
	.incbin "sound/direct_sound_samples/cries/aremilia.bin"

	.align 2
Cry_DTewi::
	.incbin "sound/direct_sound_samples/cries/dtewi.bin"

	.align 2
Cry_SMedicine::
	.incbin "sound/direct_sound_samples/cries/smedicine.bin"

	.align 2
Cry_AYuugi::
	.incbin "sound/direct_sound_samples/cries/ayuugi.bin"

	.align 2
Cry_HKeine::
	.incbin "sound/direct_sound_samples/cries/hkeine.bin"

	.align 2
Cry_ASuika::
	.incbin "sound/direct_sound_samples/cries/asuika.bin"

	.align 2
Cry_HLilyWhite::
	.incbin "sound/direct_sound_samples/cries/hlilywhite.bin"

	.align 2
Cry_SLilyBlack::
	.incbin "sound/direct_sound_samples/cries/slilyblack.bin"

	.align 2
Cry_AMurasa::
	.incbin "sound/direct_sound_samples/cries/amurasa.bin"

	.align 2
Cry_AStarSapphire::
	.incbin "sound/direct_sound_samples/cries/astarsapphire.bin"

	.align 2
Cry_AKazami::
	.incbin "sound/direct_sound_samples/cries/akazami.bin"

	.align 2
Cry_AdYukari::
	.incbin "sound/direct_sound_samples/cries/adyukari.bin"

	.align 2
Cry_AdRan::
	.incbin "sound/direct_sound_samples/cries/adran.bin"

	.align 2
Cry_AdChen::
	.incbin "sound/direct_sound_samples/cries/adchen.bin"

	.align 2
Cry_DarkAlice::
	.incbin "sound/direct_sound_samples/cries/darkalice.bin"

	.align 2
Cry_CSeiga::
	.incbin "sound/direct_sound_samples/cries/cseiga.bin"

	.align 2
Cry_Seiga::
	.incbin "sound/direct_sound_samples/cries/seiga.bin"

	.align 2
Cry_CTojiko::
	.incbin "sound/direct_sound_samples/cries/ctojiko.bin"

	.align 2
Cry_Kyouko::
	.incbin "sound/direct_sound_samples/cries/kyouko.bin"

	.align 2
Cry_CYoshika::
	.incbin "sound/direct_sound_samples/cries/cyoshika.bin"

	.align 2
Cry_Tojiko::
	.incbin "sound/direct_sound_samples/cries/tojiko.bin"

	.align 2
Cry_CFuto::
	.incbin "sound/direct_sound_samples/cries/cfuto.bin"

	.align 2
Cry_Futo::
	.incbin "sound/direct_sound_samples/cries/futo.bin"

	.align 2
Cry_TSanae::
	.incbin "sound/direct_sound_samples/cries/tsanae.bin"

	.align 2
Cry_Yuki::
	.incbin "sound/direct_sound_samples/cries/yuki.bin"

	.align 2
Cry_AdMokou::
	.incbin "sound/direct_sound_samples/cries/admokou.bin"

	.align 2
Cry_DYuyuko::
	.incbin "sound/direct_sound_samples/cries/dyuyuko.bin"

	.align 2
Cry_AYuyuko::
	.incbin "sound/direct_sound_samples/cries/ayuyuko.bin"

	.align 2
Cry_AdCirno::
	.incbin "sound/direct_sound_samples/cries/adcirno.bin"

	.align 2
Cry_AdMystia::
	.incbin "sound/direct_sound_samples/cries/admystia.bin"

	.align 2
Cry_TKisume::
	.incbin "sound/direct_sound_samples/cries/tkisume.bin"

	.align 2
Cry_AdTewi::
	.incbin "sound/direct_sound_samples/cries/adtewi.bin"

	.align 2
Cry_AdMarisa::
	.incbin "sound/direct_sound_samples/cries/admarisa.bin"

	.align 2
Cry_AdAlice::
	.incbin "sound/direct_sound_samples/cries/adalice.bin"

	.align 2
Cry_AdLetty::
	.incbin "sound/direct_sound_samples/cries/adletty.bin"

	.align 2
Cry_AkiSisters::
	.incbin "sound/direct_sound_samples/cries/akisisters.bin"

	.align 2
Cry_Miko::
	.incbin "sound/direct_sound_samples/cries/miko.bin"

	.align 2
Cry_CMiko::
	.incbin "sound/direct_sound_samples/cries/cmiko.bin"

	.align 2
Cry_CMamizou::
	.incbin "sound/direct_sound_samples/cries/cmamizou.bin"

	.align 2
Cry_Yoshika::
	.incbin "sound/direct_sound_samples/cries/yoshika.bin"

	.align 2
Cry_SYamame::
	.incbin "sound/direct_sound_samples/cries/syamame.bin"

	.align 2
Cry_DSuwako::
	.incbin "sound/direct_sound_samples/cries/dsuwako.bin"

	.align 2
Cry_HMerlin::
	.incbin "sound/direct_sound_samples/cries/hmerlin.bin"

	.align 2
Cry_APatchouli::
	.incbin "sound/direct_sound_samples/cries/apatchouli.bin"

	.align 2
Cry_DMeiling::
	.incbin "sound/direct_sound_samples/cries/dmeiling.bin"

	.align 2
Cry_HLunasa::
	.incbin "sound/direct_sound_samples/cries/hlunasa.bin"

	.align 2
Cry_DMurasa::
	.incbin "sound/direct_sound_samples/cries/dmurasa.bin"

	.align 2
Cry_AMarisa::
	.incbin "sound/direct_sound_samples/cries/amarisa.bin"

	.align 2
Cry_Tensoku::
	.incbin "sound/direct_sound_samples/cries/tensoku.bin"

	.align 2
Cry_SMarisa::
	.incbin "sound/direct_sound_samples/cries/smarisa.bin"

	.align 2
Cry_DPatchouli::
	.incbin "sound/direct_sound_samples/cries/dpatchouli.bin"

	.align 2
Cry_CKasen::
	.incbin "sound/direct_sound_samples/cries/ckasen.bin"

	.align 2
Cry_Kasen::
	.incbin "sound/direct_sound_samples/cries/kasen.bin"

	.align 2
Cry_Gomaseki::
	.incbin "sound/direct_sound_samples/cries/gomaseki.bin"

	.align 2
Cry_CWakasagi::
	.incbin "sound/direct_sound_samples/cries/cwakasagi.bin"

@PUPPETPY

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
