gTrickHouse_Mechadoll_CKeine::
	.string "CKEINE$"

gTrickHouse_Mechadoll_DYuyuko::
	.string "DYUYUKO$"

gTrickHouse_Mechadoll_TShou::
	.string "TSHOU$"

gTrickHouse_Mechadoll_CShinGyoku::
	.string "CSHINGYOKU$"

gTrickHouse_Mechadoll_AHina::
	.string "AHINA$"

gTrickHouse_Mechadoll_TKogasa::
	.string "TKOGASA$"

gTrickHouse_Mechadoll_TMedicine::
	.string "TMEDICINE$"

gTrickHouse_Mechadoll_CMinoriko::
	.string "CMINORIKO$"

gTrickHouse_Mechadoll_HShizuha::
	.string "HSHIZUHA$"

gTrickHouse_Mechadoll_Tenma::
	.string "TENMA$"

gTrickHouse_Mechadoll_HLunasa::
	.string "HLUNASA$"

gTrickHouse_Mechadoll_SSariel::
	.string "SSARIEL$"

gTrickHouse_Mechadoll_DYuyuko2::
	.string "DYUYUKO$"

gTrickHouse_Mechadoll_DSuwako::
	.string "DSUWAKO$"

gTrickHouse_Mechadoll_HLunasa2::
	.string "HLUNASA$"

gTrickHouse_Mechadoll_DYuyuko3::
	.string "DYUYUKO$"

gTrickHouse_Mechadoll_CMinoriko2::
	.string "CMINORIKO$"

gTrickHouse_Mechadoll_ATewi::
	.string "ATEWI$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "BURN HEAL$"

gTrickHouse_Mechadoll_HarborMail::
	.string "HARBOR MAIL$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Same price$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "Nothing$"

gTrickHouse_Mechadoll_CostMore::
	.string "They will cost more.$"

gTrickHouse_Mechadoll_CostLess::
	.string "They will cost less.$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "Same price$"

gTrickHouse_Mechadoll_Male::
	.string "Male$"

gTrickHouse_Mechadoll_Female::
	.string "Female$"

gTrickHouse_Mechadoll_Neither::
	.string "Neither$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Elderly men$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Elderly ladies$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Same number$"

gTrickHouse_Mechadoll_None::
	.string "None$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
